// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEcltCMKUWaS7nSZ_uLu-En1Gv6N_I6I',
    appId: '1:414278712705:web:4c58ab63fa808353a0bc80',
    messagingSenderId: '414278712705',
    projectId: 'to-do-app-70170',
    authDomain: 'to-do-app-70170.firebaseapp.com',
    storageBucket: 'to-do-app-70170.firebasestorage.app',
    measurementId: 'G-4SK4YKQ5EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjs3hsg711qEljyeiH1Uaj0ZNYqHVoPes',
    appId: '1:414278712705:android:4b4202d3a0450815a0bc80',
    messagingSenderId: '414278712705',
    projectId: 'to-do-app-70170',
    storageBucket: 'to-do-app-70170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qgmW1nO7obOzdSpX4d5MssmGp0OhRTc',
    appId: '1:414278712705:ios:59eef40da9f40ecca0bc80',
    messagingSenderId: '414278712705',
    projectId: 'to-do-app-70170',
    storageBucket: 'to-do-app-70170.firebasestorage.app',
    iosBundleId: 'com.example.shopSmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5qgmW1nO7obOzdSpX4d5MssmGp0OhRTc',
    appId: '1:414278712705:ios:59eef40da9f40ecca0bc80',
    messagingSenderId: '414278712705',
    projectId: 'to-do-app-70170',
    storageBucket: 'to-do-app-70170.firebasestorage.app',
    iosBundleId: 'com.example.shopSmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALEcltCMKUWaS7nSZ_uLu-En1Gv6N_I6I',
    appId: '1:414278712705:web:fcdd4bb0b403940ba0bc80',
    messagingSenderId: '414278712705',
    projectId: 'to-do-app-70170',
    authDomain: 'to-do-app-70170.firebaseapp.com',
    storageBucket: 'to-do-app-70170.firebasestorage.app',
    measurementId: 'G-BE1NXZB3TD',
  );
}
